# Generated by Django 3.1.3 on 2020-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=15)),
                ('Description', models.TextField()),
            ],
        ),
    ]
