# Generated by Django 3.1.3 on 2020-11-22 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News1', '0006_auto_20201122_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 19, 6, 12, 278137, tzinfo=utc)),
        ),
    ]
