# Generated by Django 3.1.3 on 2020-11-22 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News1', '0007_auto_20201122_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Thumb',
            new_name='thumb',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 19, 21, 43, 432563, tzinfo=utc)),
        ),
    ]
